// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjKrlDNykb6f92RGTzm2gy4acjeHbd4Ak',
    appId: '1:999217346837:web:e580b0c1e0aa5a6e49911c',
    messagingSenderId: '999217346837',
    projectId: 'jobhub-app',
    authDomain: 'jobhub-app.firebaseapp.com',
    storageBucket: 'jobhub-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8rPQB0aDMHC5aE5bASvlrShYNVbfMgkY',
    appId: '1:999217346837:android:52bc72a3e3cf4bbe49911c',
    messagingSenderId: '999217346837',
    projectId: 'jobhub-app',
    storageBucket: 'jobhub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClRd3J76JMcMtygX-WB3vjYh2u7w0mmp8',
    appId: '1:999217346837:ios:8bfde5edafbca35a49911c',
    messagingSenderId: '999217346837',
    projectId: 'jobhub-app',
    storageBucket: 'jobhub-app.appspot.com',
    iosClientId: '999217346837-nd45u480t33bjigrv8jku49bdukh7nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClRd3J76JMcMtygX-WB3vjYh2u7w0mmp8',
    appId: '1:999217346837:ios:8bfde5edafbca35a49911c',
    messagingSenderId: '999217346837',
    projectId: 'jobhub-app',
    storageBucket: 'jobhub-app.appspot.com',
    iosClientId: '999217346837-nd45u480t33bjigrv8jku49bdukh7nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobhub',
  );
}
